import {StyleSheet, Dimensions, Platform} from 'react-native';
import {Colors, Fonts, Sizes} from '../../../../constants/theme';

export const styles = StyleSheet.create({
  headerRoot: {
    paddingHorizontal: 30,
    gap: 5,
    paddingVertical: 30,
    paddingTop: 50,
  },
  headerIconText: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerTitle: {
    color: Colors.AppColor,
    fontSize: Sizes.size20,
    fontFamily: Fonts.medium,
    top: 4,
  },
  headerSubTitle: {
    color: Colors.AppColor,
    fontSize: Sizes.size14,
    fontFamily: Fonts.regular,
  },
  cardContainer: {
    backgroundColor: Colors.White,
    display: 'flex',
    padding: 30,
  },
  cardTitle: {
    fontSize: Sizes.size18,
    fontFamily: Fonts.medium,
    color: Colors.AppColor,
    marginBottom: 3,
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 14,
    paddingVertical: 7,
    alignItems: 'center',
  },
  btnStyle: {
    justifyContent: 'center',
    borderRadius: 50,
    paddingVertical: 8,
    paddingHorizontal: 24,
    alignItems: 'center',
    backgroundColor: 'rgba(128, 128, 128, 0.10)',
    borderColor: 'rgba(128, 128, 128, 0.25)',
    borderWidth: 1,
  },
  btnTextStyle: {
    fontSize: Sizes.size13,
    color: Colors.ColorGrey,
    fontFamily: Fonts.medium,
  },
  reviewBtnStyle: {
    justifyContent: 'center',
    borderRadius: 50,
    paddingVertical: 5,
    paddingHorizontal: 14,
    alignItems: 'center',
    backgroundColor: 'rgba(128, 128, 128, 0.10)',
    borderColor: 'rgba(128, 128, 128, 0.25)',
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
  },
  reviewBtnTextStyle: {
    fontSize: Sizes.size13,
    color: Colors.ColorGrey,
    fontFamily: Fonts.medium,
    top: 2,
  },
  colorFamilyRoot: {
    backgroundColor: 'rgba(128, 128, 128, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(128, 128, 128, 0.25)',
    padding: 4,
    borderRadius: 50,
  },
  colorFamilyContainer: {
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 50,
  },
  locationBtnStyle: {
    justifyContent: 'center',
    borderRadius: 50,
    paddingVertical: 8,
    paddingHorizontal: 50,
    alignItems: 'center',
    backgroundColor: 'rgba(128, 128, 128, 0.10)',
    borderColor: 'rgba(128, 128, 128, 0.25)',
    borderWidth: 1,
  },
  locationBtnTextStyle: {
    fontSize: Sizes.size13,
    color: Colors.ColorGrey,
    fontFamily: Fonts.medium,
  },
  qtyBtnStyle: {
    justifyContent: 'center',
    borderRadius: 50,
    paddingVertical: 8,
    paddingHorizontal: 50,
    alignItems: 'center',
    backgroundColor: Colors.White,
    borderColor: 'rgba(128, 128, 128, 0.75)',
    borderWidth: 1,
  },
  qtyBtnTextStyle: {
    fontSize: Sizes.size13,
    color: Colors.ColorGrey,
    fontFamily: Fonts.medium,
    top: 1,
  },
  qtySeparator: {
    width: 7,
    height: 2,
    backgroundColor: 'rgba(128, 128, 128, 0.75)',
  },
  footerStyle: {
    backgroundColor: Colors.White,
    width: Dimensions.get('screen').width,
    gap: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: Platform.OS == 'ios' ? 40 : 20,
    shadowColor: Colors.AppColor,
    elevation: 30,
  },
  resetAllBtnStyle: {
    width: Dimensions.get('screen').width / 2.2,
    height: 45,
    backgroundColor: 'rgba(128, 128, 128, 0.10)',
    borderColor: 'rgba(128, 128, 128, 0.25)',
    borderWidth: 1,
    justifyContent: 'center',
    borderRadius: 50,
    alignItems: 'center',
  },
  resetAllBtnTextStyle: {
    fontSize: Sizes.size15,
    color: Colors.AppColor,
    fontFamily: Fonts.medium,
    top: 1,
  },
  applyNowBtnStyle: {
    width: Dimensions.get('screen').width / 2.2,
    height: 45,
    backgroundColor: Colors.BlueViolet,
    borderColor: Colors.BlueViolet,
    borderWidth: 1,
    justifyContent: 'center',
    borderRadius: 50,
    alignItems: 'center',
  },
  applyNowBtnTextStyle: {
    fontSize: Sizes.size15,
    color: Colors.White,
    fontFamily: Fonts.medium,
    top: 1,
  },
});
