import { Platform, StyleSheet } from 'react-native';
import { Colors, Fonts, Sizes } from '../../../../constants/theme';

export const styles = StyleSheet.create({
  cartRoot: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    gap: 20,
    borderBottomColor: Colors.SurfaceLightBlue,
    borderBottomWidth: 5,
  },
  cartDetailsRoot: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Platform.OS == 'ios' ? 0 : 15,
  },
  cartImageView: {
    width: '35%',
  },
  cartImageStyle: {
    width: 120,
    borderRadius: 15,
    height: 115,
  },
  activeBulletsView: {
    padding: 8,
    position: 'absolute',
    borderRadius: 25,
    borderWidth: 5,
    borderColor: Colors.White,
    top: -5,
    left: -5,
    elevation: 5,
  },
  cartDetails: {
    width: '63%',
  },
  cartMainText: {
    flexDirection: 'column',
    gap: 6,
  },
  cartTitleText: {
    color: Colors.AppColor,
    fontFamily: Fonts.regular,
    fontSize: Sizes.size12,
    textAlign: 'left',
  },
  cartDesText: {
    color: 'rgba(0, 0, 0, 0.75)',
    fontFamily: Fonts.regular,
    fontSize: Sizes.size10,
    textAlign: 'left',
  },
  cartRatingView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cartRatingIcon: {
    top: -2,
  },
  cartReviewsView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  reviewText: {
    fontSize: Sizes.size10,
    color: Colors.AppColor,
    fontFamily: Fonts.regular,
  },
  soldText: {
    color: Colors.ColorGrey,
    fontFamily: Fonts.medium,
    fontSize: Sizes.size10,
  },
  bottomDetailsView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },

  priceView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  disPrice: {
    color: Colors.BlueViolet,
    fontFamily: Fonts.semiBold,
    fontSize: Sizes.size14,
    top: 1,
  },
  origPrice: {
    top: 1,
    fontFamily: Fonts.regular,
    color: Colors.ColorGrey,
    textDecorationLine: 'line-through',
    fontSize: Sizes.size11,
  },
  counterView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 20,
    borderColor: Colors.BlackCoral,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderWidth: 0.5,
    position: 'absolute',
    right: 0,
    bottom: 0,
  },
  counterText: {
    fontFamily: Fonts.semiBold,
    color: Colors.AppColor,
    fontSize: Sizes.size12,
    top: 1,
  },
  separatorView: {
    borderColor: Colors.AppColor,
    borderWidth: StyleSheet.hairlineWidth,
    opacity: 0.3,
  },
  deleteBtnAllContainerStyle: {
    gap: 5,
    paddingHorizontal: 20,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: Colors.RedColorBorder,
    backgroundColor: Colors.LightRedColor,
    borderRadius: 50,
  },
  deleteAllTextStyle: {
    fontFamily: Fonts.medium,
    fontSize: Sizes.size13,
    color: Colors.RedColor,
    top: 1,
  },
  deleteBtnContainerStyle: {
    gap: 5,
    paddingHorizontal: 40,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: Colors.RedColorBorder,
    backgroundColor: Colors.LightRedColor,
    borderRadius: 50,
  },
  deleteTextStyle: {
    fontFamily: Fonts.medium,
    fontSize: Sizes.size10,
    color: Colors.RedColor,
    top: 1,
  },
  editBtnContainerStyle: {
    paddingHorizontal: 35,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: Colors.RomanSilver,
    gap: 5,
    backgroundColor: Colors.White,
    borderRadius: 50,
  },
  editTextStyle: {
    fontFamily: Fonts.medium,
    fontSize: Sizes.size10,
    color: Colors.AppColor,
    top: 1,
  },
  buttonsView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 20,
    paddingVertical: Platform.OS == 'ios' ? 10 : 0,
  },
  checkboxContainer: {
    paddingTop: 20,
    paddingBottom: 20,
    paddingHorizontal: 25,
    backgroundColor: Colors.White,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 10,
    borderColor: Colors.SurfaceLightBlue,
  },
  checkbox: {
    borderRadius: 60,
  },
  headerText: {
    color: Colors.AppColor,
    fontFamily: Fonts.semiBold,
    fontSize: Sizes.size18,
    top: 1.5,
    textTransform: 'capitalize',
  },
  checkAllText: {
    fontFamily: Fonts.medium,
    fontSize: Sizes.size13,
    color: Colors.AppColor,
    top: 1,
  },
  footerRoot: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: Colors.White,
    shadowColor: Colors.AppColor,
    elevation: 30,
  },
  finalPaymentdetails: {
    paddingVertical: 10,
    borderBottomColor: Colors.lightGrey,
    borderBottomWidth: 1,
    gap: 10,
  },
  paymentInfoView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paymentInfoText: {
    color: Colors.AppColor,
    fontFamily: Fonts.regular,
    fontSize: Sizes.size14,
  },
  subTotalText: {
    top: 1,
    fontFamily: Fonts.semiBold,
    color: Colors.AppColor,
    fontSize: Sizes.size14,
  },
  shippingFeeText: {
    fontFamily: Fonts.Bold,
    color: Colors.GreenColor,
    fontSize: Sizes.size14,
  },
  vatText: {
    top: 1,
    fontFamily: Fonts.medium,
    color: Colors.AppColor,
    fontSize: Sizes.size14,
  },
  totalText: {
    top: 1,
    fontFamily: Fonts.semiBold,
    color: Colors.AppColor,
    fontSize: Sizes.size16,
  },
  totalPaymentInfoView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
  },
});
