import {StyleSheet} from 'react-native';
import {Colors, Fonts, Sizes} from '../../../../../../constants/theme';

export const styles = StyleSheet.create({
  root: {
    backgroundColor: Colors.White,
    flex: 1,
  },
  childvaccinePeriodRoot: {
    paddingVertical: 30,
    backgroundColor: Colors.White,
    borderTopWidth: 10,
    borderTopColor: Colors.SurfaceLightBlue,
    borderBottomWidth: 10,
    borderBottomColor: Colors.SurfaceLightBlue,
  },
  periodsView: {
    paddingHorizontal: 20,
  },
  periodBtnStyle: {
    width: 130,
    paddingVertical: 10,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  periodBtnTextStyle: {
    fontSize: Sizes.size12,
    fontFamily: Fonts.semiBold,
    top: 1,
  },
  separatorLine: {
    height: 3,
    width: 40,
    backgroundColor: Colors.SurfaceLightBlue,
    alignSelf: 'center',
  },
  periodRoot: {
    paddingHorizontal: 20,
    paddingTop: 40,
    borderColor: Colors.SurfaceLightBlue,
    gap: 20,
  },
  birthBtnStyle: {
    paddingVertical: 12,
    backgroundColor: Colors.AppColor,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: Colors.AppColor,
  },
  birthBtnTextStyle: {
    fontSize: Sizes.size16,
    fontFamily: Fonts.semiBold,
    top: 1,
    color: Colors.White,
  },
  statusContainer: {
    borderRadius: 50,
    backgroundColor: Colors.BlueVioletLight,
    borderWidth: 1,
    borderColor: Colors.BlueViolet,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 15,
    paddingVertical: 15,
    marginBottom: -20
  },
  statusCountViewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  statusCountView: {
    borderRadius: 50,
    paddingHorizontal: 5,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusCount: {
    fontFamily: Fonts.medium,
    fontSize: Sizes.size11,
    color: Colors.White,
    top: 1,
  },
  statusText: {
    fontFamily: Fonts.semiBold,
    fontSize: Sizes.size11,
    color: Colors.BlueViolet,
    top: 1,
  },
  accordionBtnView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 30,
    paddingHorizontal: 25,
    borderColor: Colors.BlackCoral,
    paddingVertical: 15,
    borderWidth: 0.5,
    marginTop: 25
  },
  accordionBtnLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  accordionBtnRightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  accordionTitle: {
    fontFamily: Fonts.semiBold,
    fontSize: Sizes.size14,
    color: Colors.AppColor,
    top: 2,
  },
  vaccineStatus: {
    fontFamily: Fonts.medium,
    fontSize: Sizes.size13,
    color: Colors.MetallicSilver,
  },
  accordionDescView: {
    paddingHorizontal: 25,
    borderBottomColor: Colors.BlackCoral,
    borderWidth: 0.5,
    borderTopWidth: -0.5,
    paddingVertical: 15,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    paddingBottom: 20,
  },
  accordionDesc: {
    fontFamily: Fonts.regular,
    fontSize: Sizes.size13,
    color: Colors.AppColor,
    lineHeight: 18,
    paddingTop: 15,
  },
  accordionDescLink: {
    fontFamily: Fonts.semiBold,
    fontSize: Sizes.size13,
    color: Colors.BlueViolet,
  },
  accordionDescChildDue: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  accordionDescChildReminder: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  accordionDescTitle: {
    fontFamily: Fonts.medium,
    fontSize: Sizes.size13,
    color: Colors.AppColor,
    marginTop: 10,
  },
  accordionDescBtn: {
    backgroundColor: Colors.BlueVioletLight,
    borderWidth: 1,
    borderColor: Colors.BlueViolet,
    borderRadius: 50,
    paddingVertical: 2,
    paddingHorizontal: 12,
    top: 3,
  },
  accordionDescBtnLink: {
    fontFamily: Fonts.semiBold,
    fontSize: Sizes.size11,
    color: Colors.BlueViolet,
    top: 1,
  },
  addGrowthChartText: {
    fontFamily: Fonts.semiBold,
    fontSize: Sizes.size16,
    textAlign: 'center',
    top: 1,
    color: Colors.BlueViolet,
  },
});
