import { StyleSheet } from 'react-native';
import { Colors, Fonts, Sizes } from '../../../../constants/theme';

export const styles = StyleSheet.create({
    toggleSwitch: {
        width: 52,
        height: 28,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: Colors.AppColor,
    },
    toggleCircle: {
        width: 22,
        height: 22,
        borderRadius: 18,
        backgroundColor: Colors.White,
    },
    saveCardsRoot: {
        backgroundColor: Colors.White,
        paddingHorizontal: 20,
        paddingVertical: 30,
        marginVertical: 10,
        gap: 25,
    },
    cardHeadingView: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomColor: Colors.lightGrey,
        borderBottomWidth: 1,
        paddingBottom: 10,
    },
    cardHeadingText: {
        color: Colors.AppColor,
        fontFamily: Fonts.semiBold,
        fontSize: Sizes.size18,
        top: 1
    },
    headingEditText: {
        textDecorationLine: 'underline',
        color: Colors.BlueViolet,
        fontSize: Sizes.size16,
        fontFamily: Fonts.medium,
    },
    methodsBtnView: {
        gap: 18,
    },
    creditBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        paddingVertical: 15,
        borderWidth: 0.5,
        borderColor: Colors.BlackCoral,
        borderRadius: 30,
    },
    btnTextView: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 9,
    },
    btnText: {
        top: 1,
        fontFamily: Fonts.semiBold,
        fontSize: Sizes.size14,
        color: Colors.AppColor,
    },
    radioView: {
        borderColor: Colors.AppColor,
        borderWidth: 1,
        padding: 2,
        borderRadius: 80,
    },
    radioBg: {
        backgroundColor: Colors.BlueViolet,
        padding: 7,
        margin: 2,
        borderRadius: 80,
    },
    radioOff: {
        padding: 9,
    },
    addCardsRoot: {
        backgroundColor: Colors.White,
        paddingHorizontal: 20,
        paddingVertical: 30,
        paddingBottom: 40,
        gap: 25,
    },
    inputsView: {
        gap: 18,
    },
    cardInputs: {
        paddingHorizontal: 25,
        paddingVertical: 13,
        borderWidth: 0.5,
        borderColor: Colors.BlackCoral,
        borderRadius: 30,
        color: Colors.AppColor,
        fontFamily: Fonts.regular,
        fontSize: Sizes.size14,
    },
    bottomInputsView: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 20,
    },
    cvvInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 5,
        borderWidth: 0.5,
        color: Colors.AppColor,
        borderColor: Colors.BlackCoral,
        borderRadius: 30,
        width: '47%',
    },
    cvvInput: {
        top: 2,
        color: Colors.AppColor,
        paddingHorizontal: 25,
        width: '80%',
        fontFamily: Fonts.regular,
        fontSize: Sizes.size14,
    },
    dateInput: {
        paddingHorizontal: 25,
        fontFamily: Fonts.regular,
        fontSize: Sizes.size14,
        color: Colors.AppColor,
        paddingVertical: 15,
        borderWidth: 0.5,
        borderColor: Colors.BlackCoral,
        borderRadius: 30,
        width: '47%',
    },
    saveCardOptionView: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        paddingHorizontal: 5,
        marginTop: 20,
    },
    saveCardOptionHeading: {
        fontSize: Sizes.size17,
        color: Colors.AppColor,
        fontFamily: Fonts.medium,
    },
    saveCardOptionDes: {
        fontFamily: Fonts.regular,
        fontSize: Sizes.size13,
        color: Colors.AppColor,
        width: '90%',
        lineHeight: 15
    },

    footerStyle: {
        shadowColor: Colors.AppColor,
        elevation: 30,
        shadowOffset: { width: 10, height: 10 },
        backgroundColor: Colors.White,
        paddingHorizontal: 20,
        paddingBottom: 20,
        paddingTop: 30,
        gap: 20,
    },
    footerText: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    footerTotalText: {
        color: Colors.AppColor,
        fontFamily: Fonts.semiBold,
        fontSize: Sizes.size19,
    },
    footerSubtotalText: {
        color: Colors.AppColor,
        fontSize: Sizes.size15,
        fontFamily: Fonts.regular,
    },
    footerBtnStyle: {
        padding: 15,
        backgroundColor: Colors.BlueViolet,
        justifyContent: 'center',
        borderRadius: 50,
        alignItems: 'center',
    },
    footerBtnTextStyle: {
        top: 3,
        color: Colors.White,
        fontSize: Sizes.size16,
        fontFamily: Fonts.semiBold,
    },
});  